chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path('', views.home, name='home'),
    path('<str:room>/', views.room, name='room'),
    path('checkview', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [

    path('', include('textbook_exchange.urls')),
    path('textbook/', include('textbook_exchange.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('logout', LogoutView.as_view(), name='logout'),
    path('', include(("chat.urls", "chat"), namespace="chat"))

]

textbook_exchange/urls.py
from django.urls import path, include
import requests

from . import views

urlpatterns = [
    path('', views.mainView, name = 'mainView'),
    path('search/', views.searchView, name = 'searchView'),
    path('classes/', views.homeView, name = 'homeView'),
    path('departments/', views.DeptSearchView, name = 'department_list'),
    path('departments/<str:subject>/', views.ClassFilterView.as_view(), name = 'class_list'),
    path('submission/', views.SubmissionView, name = 'SubmissionView'),
    path('resubmission/', views.ResubmissionView, name = "ResubmissionView"),
    path('departments/<str:subject>/<str:catalog_number>/', views.ClassInfo, name = 'class_info'),
    path('allbooks/', views.AllBookView.as_view(), name = 'allbooks'),
    path('details/<int:book_id>/', views.display_book_info, name = 'bookdetails'),
    path('update_profile/', views.UpdateProfileView, name = 'updateprofileview'),
    path('profile/', views.profileView, name = 'accountView'),
    path('removeFavorite', views.removeFavorite, name = 'removeFavorite'),
    path('addFavorite', views.addFavorite, name = 'addFavorite'),
    path('removeFriend', views.removeFriend, name = 'removeFriend'),
    path('addFriend', views.addFriend, name = 'addFriend'),
    path('removeListing', views.removeListing, name = 'removeListing'),
    path('requestFriend', views.requestFriend, name = 'requestFriend'),
    path('removeFriendRequest', views.removeFriendRequest, name = 'removeFriendRequest'),
]

textbook_exchange/models.py
from django.db import models
from django.forms import ModelForm
from django.forms import modelformset_factory
from django.contrib.auth.models import User

# Create your models here.
# department model which follows the API call: http://luthers-list.herokuapp.com/api/deptlist?format=json
class Department(models.Model):
    subject = models.CharField(max_length = 10)

    def __str__(self):
        return self.subject
    

# class model which follows the API call: http://luthers-list.herokuapp.com/api/dept/CS/?format=json



class Book(models.Model):
    title = models.CharField(max_length = 100)
    ISBN = models.IntegerField()
    author = models.CharField(max_length = 50)
    price = models.IntegerField()
    condition = models.CharField(max_length = 10, default = "Good")
    course = models.CharField(max_length = 20, default="CS 3240")
    instructor = models.CharField(max_length = 50, default="none")
    seller = models.CharField(max_length = 20, default="evelyn8")


    def __str__(self):
        return self.title

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'ISBN', 'author', 'price', 'course']

class Course(models.Model):
    subject = models.CharField(max_length=10) 
    catalog_number = models.CharField(max_length=14)
    instructor = models.CharField(max_length=50, default="Unknown")

class Instructor(models.Model):
    instructor = models.CharField(max_length=80)
    def __str__(self):
        return self.instructor

class Class(models.Model):
    instructor = models.CharField(max_length=80)
    instructor_email = models.CharField(max_length=80)
    course_number = models.IntegerField()
    semester_code = models.IntegerField()
    course_section = models.IntegerField() 
    subject = models.CharField(max_length=10) # this is the department code
    catalog_number = models.IntegerField()
    description = models.CharField(max_length=100) # this is the course title
    units = models.CharField(max_length=10)
    component = models.CharField(max_length=10) # LEC vs LAB
    class_capacity = models.IntegerField()
    wait_list = models.IntegerField()
    wait_cap = models.IntegerField()
    enrollment_total = models.IntegerField()
    enrollment_available = models.IntegerField()
    topic = models.CharField(max_length=100)
    meeting_days = models.CharField(max_length=14)
    start_time = models.TimeField(blank=True, null=True)
    end_time = models.TimeField(blank=True, null=True)
    location = models.CharField(max_length=100)
    book = models.ManyToManyField(Book)

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, null=True)
    year = models.IntegerField(null=True)
    # major = models.CharField(max_length=20, null=True)
    email = models.CharField(max_length=15, null=True)

    def __str__(self) -> str:
        return super().__str__()




class FriendsList(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    friends = models.ManyToManyField(User, related_name="friends", blank=True)

    def __str__(self) -> str:
        return super().__str__()


class FriendRequest(models.Model):
    sender = models.ForeignKey(User, related_name="sender", on_delete=models.CASCADE, default=None)
    receiver = models.ForeignKey(User, related_name="receiver", on_delete=models.CASCADE, default=None)


    def __str__(self) -> str:
        return super().__str__()


class FavoriteBooks(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    books = models.ManyToManyField(Book, related_name="books", blank=True)

    def __str__(self) -> str:
        return super().__str__()

# class Profile(models.Model):
#     username = models.CharField(max_length=50, default = "")
#     first_name = models.CharField(max_length=50, default = "")
#     last_name = models.CharField(max_length=50, default = "")
#     email = models.EmailField(max_length=50, default = "")
#     major = models.CharField(max_length=100, default = "")
#     graduation_year = models.IntegerField(default=0000)
#     friends = models.ManyToManyField("Profile", blank=True)

#     def __str__(self):
#         return self.username

textbook_exchange/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile




class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        help_texts = {
            'username': None,
        }
        fields = ['email', 'first_name', 'last_name']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['year']

textbook_exchange/views.py
from multiprocessing import context
from .models import Book, Department, Class, Course, FavoriteBooks, FriendRequest, FriendsList, Instructor
from django.views.generic import ListView, DetailView
from django.forms import modelformset_factory
from .forms import UserUpdateForm, ProfileUpdateForm
# from chat import views
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .filters import BookFilter, DepartmentFilter
from django.http import Http404
from django.contrib.auth.models import User
import requests


def mainView(request):
    return render(request, 'textbook_exchange/home.html')

def homeView(request):
    url = 'http://luthers-list.herokuapp.com/api/deptlist/'
    response = requests.get(url)
    data = response.json()
    context = {
        'data' : data,
    }
    return render(request, 'textbook_exchange/classes.html', context)

def searchView(request):

    books = Book.objects.all()

    filter = BookFilter(request.GET, queryset=books )
    books = filter.qs

    context = {'books':books,'filter':filter}
    return render(request, 'textbook_exchange/search.html', context)

def DeptSearchView(request):
    model = Department
    # template_name = 'textbook_exchange/departments.html'
    # context_object_name = 'department_list'

    Department.objects.all().delete()
    response = requests.get('http://luthers-list.herokuapp.com/api/deptlist/').json()
    for dept in response:
        Department.objects.create(subject=dept['subject'])
    
    departments = Department.objects.all()
    if 'q' in request.GET:
        q = request.GET['q']
        data = departments.filter(subject__icontains = q)
    else:
        data = departments
    return render(request, "textbook_exchange/departments.html", {
        "departments": data
    })
    # departments = Department.objects.filter(subject=request.GET['searchbar'])
    # context = {'departments':departments}
    # return render(request, 'textbook_exchange/departments.html', context)

def ClassSearchView(request):
    classes = Class.objects.all()
    if 'q' in request.GET:
        q = request.GET['q']
        data = classes.filter(catalog_number__icontains = q)
    else:
        data = classes
    return render(request, "textbook_exchange/classes.html", {"classes":data})
 
class ClassView(ListView):
    model = Class
    template_name = 'textbook_exchange/classes.html'
    context_object_name = 'class_load'

    def get_queryset(self):
        department = self.kwargs['subject']
        Class.objects.all().delete()

        response = requests.get('http://luthers-list.herokuapp.com/api/dept/' + department).json()
        for course in response:
            Class.objects.create(
                instructor=course['instructor']['name'],
                instructor_email=course['instructor']['email'],
                course_number=course['course_number'],
                semester_code=course['semester_code'],
                course_section=course['course_section'],
                subject=course['subject'],
                catalog_number=course['catalog_number'],
                description=course['description'],
                units=course['units'],
                component=course['component'],
                class_capacity=course['class_capacity'],
                wait_list=course['wait_list'],
                wait_cap=course['wait_cap'],
                enrollment_total=course['enrollment_total'],
                enrollment_available=course['enrollment_available'],
                topic=course['topic'],
                meeting_days=course['meetings'][0]['days'],
                # TODO: format time
                start_time=None,
                end_time=None,
                location=course['meetings'][0]['facility_description'],)

        return Class.objects.all()


def ResubmissionView(request):
    
    return render(request, 'textbook_exchange/resubmission.html')

def CourseView(request):
    model = Course
    department_list = Department.objects.all()
    Course.objects.all().delete()
    for department in department_list:
        depart = department.subject
        response = requests.get('http://luthers-list.herokuapp.com/api/dept/' + depart).json()
        for x in response:
            if(x['instructor']['name'] == "-"):
                instruct = "N/A"
            else:
                instruct = x['instructor']['name']
            if (Course.objects.filter(subject=x['subject'], catalog_number=x['catalog_number'], instructor = instruct).exists()):
                depart = depart
            else:
                Course.objects.create(
                subject=x['subject'],
                catalog_number=x['catalog_number'],
                instructor=instruct)
    return redirect('ResubmissionView')

def InstructorView(request):
    model = Instructor
    department_list = Department.objects.all()
    for department in department_list:
        depart = department.subject
        response = requests.get('http://luthers-list.herokuapp.com/api/dept/' + depart).json()
        for x in response:
            if (Instructor.objects.filter(instructor=x['instructor']['name']).exists()):
                depart = depart
            else:
                Instructor.objects.create(
                instructor=x['instructor']['name'])
    return redirect('ResubmissionView')

def SubmissionView(request):
    try:
        courseInst = request.POST['course']
        num = courseInst.index("-")
        cour = courseInst[:num-1]
        instr = courseInst[num+2:]
        book = Book(title=request.POST['title'], ISBN = request.POST['isbn'], author = request.POST['author'], price = request.POST['price'], condition = request.POST['condition'], course = cour,instructor = instr, seller = request.POST['seller'])
        book.save()
        return redirect('ResubmissionView')
    except(KeyError):
        instructor_list = Instructor.objects.all().order_by("instructor")
        course_list = Course.objects.all().order_by("subject")
        context = {'instructors': instructor_list, 'courses': course_list}
        return render(request, 'textbook_exchange/textbooksubmission.html', context)


class AllBookView(ListView):
    model = Book
    template_name = 'textbook_exchange/bookdisplay.html'
    context_object_name = 'textbook_list'

    def display_all_textbooks(request):

        textbook_list = Book.objects.all()
        context = {'textbook_list': textbook_list}
        return render(request, 'textbook_exchange/bookdisplay.html',context)


def UpdateProfileView(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        if u_form.is_valid():
            u_form.save()
            return redirect('accountView')

    else:
        u_form = UserUpdateForm(instance=request.user)
        

    context = {
        'u_form': u_form,
        
        

    }

    return render(request, 'textbook_exchange/update_profile.html', context)





class ClassInfoView(ListView):
    model = Class
    template_name = 'textbook_exchange/classinfo.html'
    context_object_name = 'class_list'

    def get_queryset(self):
        department = self.kwargs['subject']
        Class.objects.all().delete()

        response = requests.get('http://luthers-list.herokuapp.com/api/dept/' + department).json()
        for course in response:
            Class.objects.create(
                instructor=course['instructor']['name'],
                instructor_email=course['instructor']['email'],
                course_number=course['course_number'],
                semester_code=course['semester_code'],
                course_section=course['course_section'],
                subject=course['subject'],
                catalog_number=course['catalog_number'],
                description=course['description'],
                units=course['units'],
                component=course['component'],
                class_capacity=course['class_capacity'],
                wait_list=course['wait_list'],
                wait_cap=course['wait_cap'],
                enrollment_total=course['enrollment_total'],
                enrollment_available=course['enrollment_available'],
                topic=course['topic'],
                meeting_days=course['meetings'][0]['days'],
                start_time=None,
                end_time=None,
                location=course['meetings'][0]['facility_description'],)

        return Class.objects.all()

def ClassInfo(request, subject, catalog_number):

    template_name = 'textbook_exchange/classinfo.html'
    book_list = Book.objects.all()
    full_name = subject + " " + str(catalog_number)
    books = []
    for book in book_list:
        if book.course == full_name:
            books.append(book)
    context = {
        'subject': subject,
        'catalog_number': catalog_number,
        'books': books,
    }
    return render(request, template_name, context)

class ClassFilterView(ListView):
    model = Class
    template_name = 'textbook_exchange/classes.html'
    context_object_name = 'class_list'


    def get_queryset(self):
        department = self.kwargs['subject']
        Class.objects.all().delete()

        response = requests.get('http://luthers-list.herokuapp.com/api/dept/' + department).json()
        catalog = []
        for course in response:
            if course['catalog_number'] not in catalog:
                catalog.append(course['catalog_number'])
                Class.objects.create(
                    instructor=course['instructor']['name'],
                    instructor_email=course['instructor']['email'],
                    course_number=course['course_number'],
                    semester_code=course['semester_code'],
                    course_section=course['course_section'],
                    subject=course['subject'],

textbook_exchange/templates/textbook_exchange/bookdetails.html
<!DOCTYPE html>

{# Load the tag library #}
{% load bootstrap5 %}
{% load static %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

<html>
<head>
  <title>{{Book.title}}</title>
  <link rel="icon" type="image/x-icon" href="https://www.freeiconspng.com/thumbs/book-icon/book-stack-icon--icon-search-engine-16.png">

</head>
<body>
  <style>
    body {
      background-color:#FCF9F7;
  }
  .navbar-brand:hover, .nav-link:hover, .dropdown-item:hover {
  opacity: 0.8;

  }
  </style>
         <!-- Navbar  -->
         <nav class="navbar navbar-dark sticky-top" style="background-color: #6db8d2;">
          <div class="container-fluid" style="display:flex;">
            <a class="navbar-brand" style="font-size:25px;" href="{% url 'mainView' %}">
              <img src="https://www.freeiconspng.com/thumbs/book-icon/book-stack-icon--icon-search-engine-16.png" alt="" width="45" height="36" class="d-inline-block align-text-top">
              Textbooks For Sale
            </a>
            <nav class="nav" style="display:flex; align-items:center; justify-content:center;">
                <a class="nav-link" style="color:white; font-size:20px;" href="{% url 'searchView' %}">Search</a>
              <!-- <a class="nav-link" style="color:white; font-size:20px;" href="{% url 'allbooks' %}">All Listings</a> -->
              <a class="nav-link" style="color:white; font-size:20px;" href="{% url 'department_list' %}">Classes</a>
              <a class="nav-link" style="color:white; font-size:20px;" href="{% url 'SubmissionView' %}">Sell</a>
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'accountView' %}" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" style="border-radius: 50%; max-width: 45px; max-height: 45px;">
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <!--<li><a class="dropdown-item" href="https://textbooksforsale.herokuapp.com/accounts/logout/">Logout</a></li>-->
                  <li><a class="dropdown-item" href="{% url 'accountView' %}">Account</a></li>
                  <!-- <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li> -->
                  <li><a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#exampleModal">Logout</a></li>
                </ul>
               </div>
             </nav>

          </div>
        </nav>
        <!-- Navbar -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel" style="font-size:30px;">Confirm Logout</h5>
      <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body" style="font-size:24px;">
      Are you sure you want to log out?
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="font-size:20px;">Cancel</button>
      <form action="{% url 'logout' %}">
      <button type="submit" class="btn btn-primary" style="font-size:20px;">Logout</button>
      </form>
    </div>
  </div>
</div>
</div>

<script>
var myModal = document.getElementById('myModal')
var myInput = document.getElementById('myInput')

myModal.addEventListener('shown.bs.modal', function () {
  myInput.focus()
})
</script>


  <div style="display:flex; flex-align:center; justify-content:center; margin:50px;">
    <div class="col-lg-4" style="max-width:300px;  margin-right:20px;">
      <div class="card mb-4">
        <div class="card-body text-center" style="min-height:427px;">
          <h2 style="margin:10px;">Seller</h2>
          <img
            src="https://static.vecteezy.com/system/resources/previews/005/502/069/non_2x/illustration-cute-cartoon-animal-rabbit-with-scarf-logo-icon-vector.jpg"
            alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
          <h5 style="margin:10px; margin-bottom:20px;">{{Book.seller}}</h5>
          <div class="d-flex justify-content-center margin:20px;">
            {%if Book.seller != user.username %}
            <form style="display: inline-block; ;" action="{% url 'requestFriend' %}" method="post">
              {% csrf_token %}
              <button name="friend" class="btn" value="{{ Book.seller }}" type="submit">Add
                Friend</button>
            </form>
            {% endif %}
          </div>
          <div style="margin:20px;">
            <form id="post-form" method="POST" action="{% url 'chat:checkview' %}">
              {% csrf_token %}
              <input type="hidden" name="room_name" id="room_name" width="100px" value="{{ Book.title }}" />
              <input type="hidden" name="username" id="username" width="100px" value="{{ user.username }}" />
              <input type="submit" class="btn2 " value="Message">
            </form>
          </div>
        </div>
      </div>
    </div>


  <div class="card mb-3" style="min-width: 800px; max-height: 428px;">
    <div class="row g-0">
      <div class="col-md-4">
        {% if Book.pk|divisibleby:9 %}
        <img src="https://media.istockphoto.com/id/1077215560/vector/isometric-book-icon-in-flat-design-style.jpg?s=612x612&w=0&k=20&c=3HrjcKK-rKTjZ5cn81fWdBKySkP4-QXb2x9_D6O_dyw="
        alt="Book"
        class="img-fluid rounded-start"
        style="min-height:427px;"
        />
        {% elif Book.pk|divisibleby:7 %}
        <img
        src="https://media.istockphoto.com/id/1019517774/vector/book-color-icon-on-blue-book-for-reading-and-studying-at-school.jpg?s=612x612&w=0&k=20&c=jnSKNROqE5ro5cKQUieolnoa7yB-jK0TQuNQcAL9Y1w="
        alt="Book"
        class="img-fluid rounded-start"
        style="min-height:427px;"
        />
        {% elif Book.pk|divisibleby:6 %}
        <img
        src="https://media.istockphoto.com/id/546772166/vector/open-book-icon.jpg?s=612x612&w=0&k=20&c=6XqXy9NSO5-9ZOUeT7fWRBRdsGwGMPIjrwduTYvfLXc="
        alt="Book"
        class="img-fluid rounded-start"
        style="min-height:427px;"
        />
        {% elif Book.pk|divisibleby:5 %}
        <img
        src="https://media.istockphoto.com/id/960184330/vector/open-green-book-flat-design.jpg?s=612x612&w=0&k=20&c=B-1Zh7YfegftUo7mp-aUSnGpjsjWAZunqQK8i_rcQWc="
        alt="Book"
        class="img-fluid rounded-start"
        style="min-height:427px;"
        />
        {% elif Book.pk|divisibleby:4 %}
        <img
        src="https://media.istockphoto.com/id/1144204165/vector/open-book-icon-in-flat-style-literature-vector-illustration-on-isolated-background-library.jpg?s=612x612&w=0&k=20&c=Bvs3P5rFspHINJmLXgVl7c8U-YBg6Cv3jFTPUispF5A="
        alt="Book"
        class="img-fluid rounded-start"
        style="min-height:427px;"
        />
        {% elif Book.pk|divisibleby:3 %}
        <img
        src="https://media.istockphoto.com/id/1267515978/vector/open-book-isometric-flat-design-vector-illustration.jpg?s=612x612&w=0&k=20&c=DE9HjAGw7ClVUEHY8ZnUIYJZzcYOCRoTXe5nIL9IJXc="
        alt="Book"
        class="img-fluid rounded-start"
        style="min-height:427px;"
        />
        {% elif Book.pk|divisibleby:2 %}
        <img
        src="https://media.istockphoto.com/id/1152677695/vector/book-flat-design-style-on-blue-background-education-vector-illustration.jpg?s=612x612&w=0&k=20&c=x-ciX-Zigt8CZKzpRt-PVGpK3n66raEVMTDG1CaT19A="
        alt="Book"
        class="img-fluid rounded-start"
        style="min-height:427px;"
        />
        {% else %}
        <img
        src="https://media.istockphoto.com/id/1415602825/vector/open-empty-book-purple-pink-icon-isolated-on-blue-vector-illustration.jpg?s=612x612&w=0&k=20&c=XjyD_WBBScY9cpnLYM1XkfkHV53o01x7F6BcMaYtz5M="
        alt="Book"
        class="img-fluid rounded-start"
        style="min-height:427px;"
        />
        {% endif %}
      </div>
      <div class="col-md-8">
        <div class="card-body" style="margin:20px;">
          <h1>{{Book.title}}</h1>
          <h2>By {{Book.author}}</h2>
          <br>
        <div style="display:flex; margin-top:20px; background-color:white; border:none;" class="card-footer">
          <div style="text-align:center; margin-top:30px; margin-right:10px;">
            <h1>${{Book.price}}</h1>
            {% if Book.condition == "New" %}
            <h5 class="text-success" style="margin:20px;">{{Book.condition}}</h5>
            {% elif Book.condition == "Very Good" %}
            <h5 class="text-primary" style="margin:20px;">{{Book.condition}}</h5>
            {% elif Book.condition == "Good" %}
            <h5 class="text-info" style="margin:20px;">{{Book.condition}}</h5>
            {% elif Book.condition == "Fair" %}
            <h5 class="text-warning" style="margin:20px;">{{Book.condition}}</h5>
            {% else %}
            <h5 class="text-danger" style="margin:20px;">{{Book.condition}}</h5>
            {% endif %}
            <div class="d-flex flex-column mt-4">
              <form style="display: inline-block; ;" action="{% url 'addFavorite' %}" method="post">
                {% csrf_token %}
                <button name="book" class="btn" value="{{ Book.pk }}" type="submit">Favorite</button>
              </form>
            </div>
          </div>

          <div class="border-sm-start-none border-start" style="margin-left:20px; margin-top:30px;">
            <div style="margin-left:20px;">
              <h5 style="margin:15px;">ISBN: <span class="text-muted">{{Book.ISBN}}</span></h5>
              <h5 style="margin:15px;">Course: <span class="text-muted">{{Book.course}}</span></h5>
              <h5 style="margin:15px;">Instructor: <span class="text-muted">{{Book.instructor}}</span></h5>
            </div>
          </div>

          <style>
            .btn {
              min-height:40px; 
              font-size:16px; 
              color:black; 
              border-radius:5px; 
              background-color: #60E4FF; 
              width:105px;
              border:0;
            }
            .btn:hover {
              color:black; 
              background-color:#54cde5;
            }
          
            .btn2 {
              min-height:40px; 
              font-size:16px; 
              color:black; 
              border-radius:5px; 
              border:0;
              min-width:105px;
              background-color:#44B5CE;
            }
          
            .btn2:hover {
              color:black; 
              background-color:#277295;
            }
          </style>  
          
        </div>
      </div>
    </div>
  </div>
</div>
</div>


<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted fixed-bottom">
  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2022 Copyright: B-17
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
    
</body>


</html>